# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  setup_local_test:
    cmds:
      - cp -R ./src/arkade ./devcontainer

  cleanup_local_test:
    cmds:
      - rm -rf ./devcontainer/arkade

  test:
    cmds:
      - devcontainer features test

  output:
    cmds:
      - mkdir -p .me/output

  package:
    depds: [output]
    cmds:
      - devcontainer features package -o .k1/output src